apiVersion: v1
kind: Service
metadata:
  name: applefe-service
spec:
  type: NodePort
  selector:
    app: test-applefe
  ports:
  - nodePort: 30080
    port: 81
    targetPort: 81

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-applefe
spec:
  selector:
    matchLabels:
      app: test-applefe
  replicas: 3
  template:
    metadata:
      labels:
        app: test-applefe
    spec:
      containers:
      - name: test-applefe
        image: amitendra/techm_mihan:FE
        ports:
        - containerPort: 81
